on: [push]

name: Octo

jobs:
  job_1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
  job_2:
    name: Run
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: run
  job_3:
    name: Upload
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with: 
          path: artifact/urls.html
    